### ISSUE TITLE
A few enhancements

### ISSUE THREAD

**Issue by Ericgacoki** [Mohameddekow/RatingApp#1]
Hey @Mohameddekow, this is a cool App, I just noticed that you're using `Kotlin-Synthetics` which according to Google is getting out of support vert soon. They even stopped including this library by default in new Android projects. 

I'm yet to create a `PR` to demonstrate how this issue can be solved using `dataBinding` among other minor changes.

**Comment by Mohameddekow** [comment]
@Ericgacoki it's a cool idea to use `dataBinding` instead of `kotlin-Synthetics` i hope you will tackle this.
